apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: mock-accel-controller
  namespace: mock-device
  labels:
    app: mock-accel-controller
spec:
  selector:
    matchLabels:
      app: mock-accel-controller
  template:
    metadata:
      labels:
        app: mock-accel-controller
    spec:
      serviceAccountName: mock-accel-controller
      containers:
      - name: controller
        image: localhost/mock-accel-dra-driver:dev
        imagePullPolicy: IfNotPresent
        command:
        - /dra-driver
        args:
        - --mode=controller
        - --driver-name=mock-accel.example.com
        - --rescan-interval=30s
        - --v=5
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        volumeMounts:
        - name: sysfs
          mountPath: /sys/class/mock-accel
          readOnly: true
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi
      volumes:
      - name: sysfs
        hostPath:
          path: /sys/class/mock-accel
          type: Directory
