# Simple ResourceClaim: Request 1 device using mock-accel-pf DeviceClass
---
apiVersion: resource.k8s.io/v1alpha3
kind: ResourceClaim
metadata:
  name: simple-pf-claim
  namespace: default
spec:
  devices:
    requests:
    - name: device
      deviceClassName: mock-accel-pf
      count: 1

---
apiVersion: v1
kind: Pod
metadata:
  name: simple-test-pod
  namespace: default
spec:
  resourceClaims:
  - name: accel
    resourceClaimName: simple-pf-claim

  containers:
  - name: workload
    image: busybox
    command:
    - sh
    - -c
    - |
      echo "=== Allocated Device ==="
      env | grep MOCK_ACCEL | sort
      echo ""
      echo "Sleeping..."
      sleep 3600
    resources:
      claims:
      - name: accel
