---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kmm-hostpid-injector
  namespace: mock-device
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kmm-hostpid-injector
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kmm-hostpid-injector
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kmm-hostpid-injector
subjects:
- kind: ServiceAccount
  name: kmm-hostpid-injector
  namespace: mock-device
---
apiVersion: v1
kind: Service
metadata:
  name: kmm-hostpid-injector
  namespace: mock-device
spec:
  ports:
  - port: 443
    targetPort: 8443
  selector:
    app: kmm-hostpid-injector
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kmm-hostpid-injector
  namespace: mock-device
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kmm-hostpid-injector
  template:
    metadata:
      labels:
        app: kmm-hostpid-injector
    spec:
      serviceAccountName: kmm-hostpid-injector
      containers:
      - name: webhook
        image: registry.k8s.io/ingress-nginx/kube-webhook-certgen:v1.4.0
        imagePullPolicy: IfNotPresent
        command:
        - /bin/sh
        - -c
        - |
          cat > /webhook.py <<'WEBHOOK_EOF'
          #!/usr/bin/env python3
          import json
          import base64
          from http.server import HTTPServer, BaseHTTPRequestHandler
          import ssl

          class WebhookHandler(BaseHTTPRequestHandler):
              def do_POST(self):
                  content_length = int(self.headers['Content-Length'])
                  body = self.rfile.read(content_length)
                  admission_review = json.loads(body)

                  request = admission_review['request']
                  pod = request['object']

                  # Check if this is a KMM worker pod
                  labels = pod.get('metadata', {}).get('labels', {})
                  if labels.get('kmm.node.kubernetes.io/module.name') == 'mock-accel':
                      # Inject hostPID: true
                      patch = [
                          {
                              "op": "add",
                              "path": "/spec/hostPID",
                              "value": True
                          }
                      ]

                      response = {
                          "apiVersion": "admission.k8s.io/v1",
                          "kind": "AdmissionReview",
                          "response": {
                              "uid": request['uid'],
                              "allowed": True,
                              "patchType": "JSONPatch",
                              "patch": base64.b64encode(json.dumps(patch).encode()).decode()
                          }
                      }
                  else:
                      # Allow without modification
                      response = {
                          "apiVersion": "admission.k8s.io/v1",
                          "kind": "AdmissionReview",
                          "response": {
                              "uid": request['uid'],
                              "allowed": True
                          }
                      }

                  self.send_response(200)
                  self.send_header('Content-Type', 'application/json')
                  self.end_headers()
                  self.wfile.write(json.dumps(response).encode())

              def log_message(self, format, *args):
                  print(f"{self.address_string()} - {format % args}")

          # Generate self-signed certificate
          import subprocess
          subprocess.run([
              'openssl', 'req', '-x509', '-newkey', 'rsa:2048', '-nodes',
              '-keyout', '/tmp/key.pem', '-out', '/tmp/cert.pem',
              '-days', '365', '-subj', '/CN=kmm-hostpid-injector.mock-device.svc'
          ])

          # Start HTTPS server
          server = HTTPServer(('0.0.0.0', 8443), WebhookHandler)
          server.socket = ssl.wrap_socket(server.socket,
                                          certfile='/tmp/cert.pem',
                                          keyfile='/tmp/key.pem',
                                          server_side=True)
          print("Webhook server listening on port 8443")
          server.serve_forever()
          WEBHOOK_EOF

          chmod +x /webhook.py
          python3 /webhook.py
        ports:
        - containerPort: 8443
---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: kmm-hostpid-injector
webhooks:
- name: kmm-hostpid.mock-device.svc
  clientConfig:
    service:
      name: kmm-hostpid-injector
      namespace: mock-device
      path: "/"
    caBundle: ""
  rules:
  - operations: ["CREATE"]
    apiGroups: [""]
    apiVersions: ["v1"]
    resources: ["pods"]
    scope: "Namespaced"
  namespaceSelector:
    matchLabels:
      kmm.node.k8s.io/contains-modules: ""
  admissionReviewVersions: ["v1"]
  sideEffects: None
  failurePolicy: Ignore
